services:
  postgres:
    image: postgres:17
    container_name: nest-test-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./__data/postgres/:/var/lib/postgresql/data
